
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'Movie')
	DROP TABLE Inventory.Movie
GO

CREATE TABLE Inventory.Movie
(
	Id UNIQUEIDENTIFIER NOT NULL,
	CreatedOn DATETIMEOFFSET NULL,
	CreatedBy_Id UNIQUEIDENTIFIER NULL,
	LastModifiedOn DATETIMEOFFSET NULL,
	LastModifiedBy_Id UNIQUEIDENTIFIER NULL,
	Name NVARCHAR(255) NOT NULL,
	Format NVARCHAR(255) NOT NULL,
)

ALTER TABLE Inventory.Movie
	ADD PRIMARY KEY (Id)