
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'Game')
	DROP TABLE Inventory.Game
GO

CREATE TABLE Inventory.Game
(
	Id UNIQUEIDENTIFIER NOT NULL,
	CreatedOn DATETIMEOFFSET NULL,
	CreatedBy_Id UNIQUEIDENTIFIER NULL,
	LastModifiedOn DATETIMEOFFSET NULL,
	LastModifiedBy_Id UNIQUEIDENTIFIER NULL,
	Name NVARCHAR(255) NOT NULL,
)

ALTER TABLE Inventory.Game
	ADD PRIMARY KEY (Id)